# Site settings
title:: Dcycle U.
header-img: img/datemachinedark.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://u.dcycle.com/"
twitter_username: dcycleproject
github_username:  dcycleproject

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 99
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
